# Generated by Django 5.0.3 on 2024-04-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='member',
            new_name='members',
        ),
    ]
